// Mocks generated by Mockito 5.4.6 from annotations
// in rag_faq_document/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i18;
import 'dart:typed_data' as _i22;
import 'dart:ui' as _i21;

import 'package:dio/dio.dart' as _i7;
import 'package:dio/src/adapter.dart' as _i3;
import 'package:dio/src/cancel_token.dart' as _i20;
import 'package:dio/src/dio_mixin.dart' as _i5;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/response.dart' as _i6;
import 'package:dio/src/transformer.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:rag_faq_document/models/auth/user_response.dart' as _i10;
import 'package:rag_faq_document/models/chat/chat.dart' as _i12;
import 'package:rag_faq_document/models/document/document_status_response/document_status_response.dart'
    as _i14;
import 'package:rag_faq_document/models/message/message.dart' as _i15;
import 'package:rag_faq_document/models/token/token.dart' as _i8;
import 'package:rag_faq_document/models/upload/upload.dart' as _i13;
import 'package:rag_faq_document/repository/auth/auth_repository.dart' as _i16;
import 'package:rag_faq_document/repository/chat/chat_repository.dart' as _i23;
import 'package:rag_faq_document/repository/dio/authenticated_dio_client.dart'
    as _i11;
import 'package:rag_faq_document/repository/local_storage/local_storage.dart'
    as _i9;
import 'package:rag_faq_document/repository/message/message_repository.dart'
    as _i25;
import 'package:rag_faq_document/repository/upload/upload_repository.dart'
    as _i24;
import 'package:rag_faq_document/services/auth/auth_service.dart' as _i26;
import 'package:rag_faq_document/utils/utils.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_1 extends _i1.SmartFake
    implements _i3.HttpClientAdapter {
  _FakeHttpClientAdapter_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_2 extends _i1.SmartFake implements _i4.Transformer {
  _FakeTransformer_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_3 extends _i1.SmartFake implements _i5.Interceptors {
  _FakeInterceptors_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTokenModel_6 extends _i1.SmartFake implements _i8.TokenModel {
  _FakeTokenModel_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalStorage_7 extends _i1.SmartFake implements _i9.LocalStorage {
  _FakeLocalStorage_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultipartFile_8 extends _i1.SmartFake implements _i7.MultipartFile {
  _FakeMultipartFile_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_9 extends _i1.SmartFake implements _i10.UserResponse {
  _FakeUserResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthenticatedDioClient_10 extends _i1.SmartFake
    implements _i11.AuthenticatedDioClient {
  _FakeAuthenticatedDioClient_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChat_11 extends _i1.SmartFake implements _i12.Chat {
  _FakeChat_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadResponse_12 extends _i1.SmartFake
    implements _i13.UploadResponse {
  _FakeUploadResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentStatusResponse_13 extends _i1.SmartFake
    implements _i14.DocumentStatusResponse {
  _FakeDocumentStatusResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessage_14 extends _i1.SmartFake implements _i15.Message {
  _FakeMessage_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_15 extends _i1.SmartFake
    implements _i16.AuthRepository {
  _FakeAuthRepository_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DeviceInfoWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoWrapper extends _i1.Mock implements _i17.DeviceInfoWrapper {
  MockDeviceInfoWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<String> getDeviceName() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceName, []),
            returnValue: _i18.Future<String>.value(
              _i19.dummyValue<String>(
                this,
                Invocation.method(#getDeviceName, []),
              ),
            ),
          )
          as _i18.Future<String>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i7.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_0(this, Invocation.getter(#options)),
          )
          as _i2.BaseOptions);

  @override
  _i3.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_1(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i3.HttpClientAdapter);

  @override
  _i4.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_2(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i4.Transformer);

  @override
  _i5.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_3(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i5.Interceptors);

  @override
  set options(_i2.BaseOptions? _options) => super.noSuchMethod(
    Invocation.setter(#options, _options),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i3.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i4.Transformer? _transformer) => super.noSuchMethod(
    Invocation.setter(#transformer, _transformer),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<_i6.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i20.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i20.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i18.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<dynamic>>);

  @override
  _i18.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i20.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i18.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<dynamic>>);

  @override
  _i18.Future<_i6.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i20.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i20.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i18.Future<_i6.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i18.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i18.Future<_i6.Response<T>>);

  @override
  _i7.Dio clone({
    _i2.BaseOptions? options,
    _i5.Interceptors? interceptors,
    _i3.HttpClientAdapter? httpClientAdapter,
    _i4.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_5(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i7.Dio);
}

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i9.LocalStorage {
  MockLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i18.Future<void> saveTokens({
    required String? accessToken,
    required String? accessTokenExpiresAt,
    required String? refreshToken,
    required String? refreshTokenExpiresAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [], {
              #accessToken: accessToken,
              #accessTokenExpiresAt: accessTokenExpiresAt,
              #refreshToken: refreshToken,
              #refreshTokenExpiresAt: refreshTokenExpiresAt,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i8.TokenModel> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i18.Future<_i8.TokenModel>.value(
              _FakeTokenModel_6(this, Invocation.method(#getToken, [])),
            ),
          )
          as _i18.Future<_i8.TokenModel>);

  @override
  _i18.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i18.Future<String?>.value(),
          )
          as _i18.Future<String?>);

  @override
  _i18.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i18.Future<String?>.value(),
          )
          as _i18.Future<String?>);

  @override
  _i18.Future<void> setFirstLaunchComplete() =>
      (super.noSuchMethod(
            Invocation.method(#setFirstLaunchComplete, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> saveUser({
    required int? id,
    required String? username,
    required String? email,
    required String? createdAt,
    required String? updatedAt,
    required String? lastLoginAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [], {
              #id: id,
              #username: username,
              #email: email,
              #createdAt: createdAt,
              #updatedAt: updatedAt,
              #lastLoginAt: lastLoginAt,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [AuthenticatedDioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticatedDioClient extends _i1.Mock
    implements _i11.AuthenticatedDioClient {
  MockAuthenticatedDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_5(this, Invocation.getter(#dio)),
          )
          as _i7.Dio);

  @override
  _i9.LocalStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeLocalStorage_7(this, Invocation.getter(#storage)),
          )
          as _i9.LocalStorage);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i21.VoidCallback get onUnauthorized =>
      (super.noSuchMethod(
            Invocation.getter(#onUnauthorized),
            returnValue: () {},
          )
          as _i21.VoidCallback);

  @override
  _i18.Future<String> Function() get deviceInfoGetter =>
      (super.noSuchMethod(
            Invocation.getter(#deviceInfoGetter),
            returnValue:
                () => _i18.Future<String>.value(
                  _i19.dummyValue<String>(
                    this,
                    Invocation.getter(#deviceInfoGetter),
                  ),
                ),
          )
          as _i18.Future<String> Function());
}

/// A class which mocks [MultipartFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultipartFile extends _i1.Mock implements _i7.MultipartFile {
  MockMultipartFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);

  @override
  bool get isFinalized =>
      (super.noSuchMethod(Invocation.getter(#isFinalized), returnValue: false)
          as bool);

  @override
  _i18.Stream<_i22.Uint8List> finalize() =>
      (super.noSuchMethod(
            Invocation.method(#finalize, []),
            returnValue: _i18.Stream<_i22.Uint8List>.empty(),
          )
          as _i18.Stream<_i22.Uint8List>);

  @override
  _i7.MultipartFile clone() =>
      (super.noSuchMethod(
            Invocation.method(#clone, []),
            returnValue: _FakeMultipartFile_8(
              this,
              Invocation.method(#clone, []),
            ),
          )
          as _i7.MultipartFile);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i16.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_5(this, Invocation.getter(#dio)),
          )
          as _i7.Dio);

  @override
  _i18.Future<String> Function() get getDeviceInfoFn =>
      (super.noSuchMethod(
            Invocation.getter(#getDeviceInfoFn),
            returnValue:
                () => _i18.Future<String>.value(
                  _i19.dummyValue<String>(
                    this,
                    Invocation.getter(#getDeviceInfoFn),
                  ),
                ),
          )
          as _i18.Future<String> Function());

  @override
  _i18.Future<void> signUp({
    required String? username,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #username: username,
              #email: email,
              #password: password,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i10.UserResponse> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i18.Future<_i10.UserResponse>.value(
              _FakeUserResponse_9(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i18.Future<_i10.UserResponse>);

  @override
  _i18.Future<void> passwordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#passwordReset, [email]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i10.UserResponse> refreshAccessToken(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refreshAccessToken, [refreshToken]),
            returnValue: _i18.Future<_i10.UserResponse>.value(
              _FakeUserResponse_9(
                this,
                Invocation.method(#refreshAccessToken, [refreshToken]),
              ),
            ),
          )
          as _i18.Future<_i10.UserResponse>);

  @override
  _i18.Future<void> logout({required String? refreshToken}) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#refreshToken: refreshToken}),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i23.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.AuthenticatedDioClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeAuthenticatedDioClient_10(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i11.AuthenticatedDioClient);

  @override
  _i18.Future<List<_i12.Chat>> listChats({
    required int? pageId,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listChats, [], {
              #pageId: pageId,
              #pageSize: pageSize,
            }),
            returnValue: _i18.Future<List<_i12.Chat>>.value(<_i12.Chat>[]),
          )
          as _i18.Future<List<_i12.Chat>>);

  @override
  _i18.Future<_i12.Chat> getChat({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#getChat, [], {#id: id}),
            returnValue: _i18.Future<_i12.Chat>.value(
              _FakeChat_11(this, Invocation.method(#getChat, [], {#id: id})),
            ),
          )
          as _i18.Future<_i12.Chat>);

  @override
  _i18.Future<_i12.Chat> createChat({
    required int? documentId,
    required String? title,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChat, [], {
              #documentId: documentId,
              #title: title,
            }),
            returnValue: _i18.Future<_i12.Chat>.value(
              _FakeChat_11(
                this,
                Invocation.method(#createChat, [], {
                  #documentId: documentId,
                  #title: title,
                }),
              ),
            ),
          )
          as _i18.Future<_i12.Chat>);
}

/// A class which mocks [UploadRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadRepository extends _i1.Mock implements _i24.UploadRepository {
  MockUploadRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.AuthenticatedDioClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeAuthenticatedDioClient_10(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i11.AuthenticatedDioClient);

  @override
  _i7.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_5(this, Invocation.getter(#dio)),
          )
          as _i7.Dio);

  @override
  _i9.LocalStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeLocalStorage_7(this, Invocation.getter(#storage)),
          )
          as _i9.LocalStorage);

  @override
  _i18.Future<String> Function() get getDeviceInfoFn =>
      (super.noSuchMethod(
            Invocation.getter(#getDeviceInfoFn),
            returnValue:
                () => _i18.Future<String>.value(
                  _i19.dummyValue<String>(
                    this,
                    Invocation.getter(#getDeviceInfoFn),
                  ),
                ),
          )
          as _i18.Future<String> Function());

  @override
  _i18.Future<_i13.UploadResponse> uploadFile({
    required String? filePath,
    required String? filename,
    required String? fileType,
    _i7.MultipartFile? multipartFileForTest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [], {
              #filePath: filePath,
              #filename: filename,
              #fileType: fileType,
              #multipartFileForTest: multipartFileForTest,
            }),
            returnValue: _i18.Future<_i13.UploadResponse>.value(
              _FakeUploadResponse_12(
                this,
                Invocation.method(#uploadFile, [], {
                  #filePath: filePath,
                  #filename: filename,
                  #fileType: fileType,
                  #multipartFileForTest: multipartFileForTest,
                }),
              ),
            ),
          )
          as _i18.Future<_i13.UploadResponse>);

  @override
  _i18.Future<_i14.DocumentStatusResponse> getDocumentStatus(int? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentStatus, [documentId]),
            returnValue: _i18.Future<_i14.DocumentStatusResponse>.value(
              _FakeDocumentStatusResponse_13(
                this,
                Invocation.method(#getDocumentStatus, [documentId]),
              ),
            ),
          )
          as _i18.Future<_i14.DocumentStatusResponse>);

  @override
  _i18.Future<void> cancelUpload(dynamic documentId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelUpload, [documentId]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<bool> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i18.Future<bool>.value(false),
          )
          as _i18.Future<bool>);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i25.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.AuthenticatedDioClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeAuthenticatedDioClient_10(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i11.AuthenticatedDioClient);

  @override
  _i18.Future<_i15.Message> postMessage({
    required String? message,
    required int? sessionId,
    required int? documentId,
    required String? title,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postMessage, [], {
              #message: message,
              #sessionId: sessionId,
              #documentId: documentId,
              #title: title,
            }),
            returnValue: _i18.Future<_i15.Message>.value(
              _FakeMessage_14(
                this,
                Invocation.method(#postMessage, [], {
                  #message: message,
                  #sessionId: sessionId,
                  #documentId: documentId,
                  #title: title,
                }),
              ),
            ),
          )
          as _i18.Future<_i15.Message>);

  @override
  _i18.Future<List<_i15.Message>> listMessage({required int? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#listMessage, [], {#sessionId: sessionId}),
            returnValue: _i18.Future<List<_i15.Message>>.value(
              <_i15.Message>[],
            ),
          )
          as _i18.Future<List<_i15.Message>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i26.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.LocalStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeLocalStorage_7(this, Invocation.getter(#storage)),
          )
          as _i9.LocalStorage);

  @override
  _i16.AuthRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeAuthRepository_15(this, Invocation.getter(#repo)),
          )
          as _i16.AuthRepository);

  @override
  _i18.Future<void> signup({
    required String? username,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [], {
              #username: username,
              #email: email,
              #password: password,
            }),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> passwordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#passwordReset, [email]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<_i8.TokenModel> refreshAccessToken(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refreshAccessToken, [refreshToken]),
            returnValue: _i18.Future<_i8.TokenModel>.value(
              _FakeTokenModel_6(
                this,
                Invocation.method(#refreshAccessToken, [refreshToken]),
              ),
            ),
          )
          as _i18.Future<_i8.TokenModel>);
}
