// Mocks generated by Mockito 5.4.6 from annotations
// in rag_faq_document/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;
import 'dart:io' as _i28;
import 'dart:typed_data' as _i25;
import 'dart:ui' as _i24;

import 'package:dio/dio.dart' as _i8;
import 'package:dio/src/adapter.dart' as _i4;
import 'package:dio/src/cancel_token.dart' as _i23;
import 'package:dio/src/dio_mixin.dart' as _i6;
import 'package:dio/src/options.dart' as _i3;
import 'package:dio/src/response.dart' as _i7;
import 'package:dio/src/transformer.dart' as _i5;
import 'package:flutter/foundation.dart' as _i19;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i13;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;
import 'package:rag_faq_document/models/auth/user_response.dart' as _i10;
import 'package:rag_faq_document/models/chat/chat.dart' as _i12;
import 'package:rag_faq_document/models/document/document_status_response/document_status_response.dart'
    as _i16;
import 'package:rag_faq_document/models/message/message.dart' as _i17;
import 'package:rag_faq_document/models/upload/upload.dart' as _i15;
import 'package:rag_faq_document/models/upload/upload_presign/upload_presign.dart'
    as _i14;
import 'package:rag_faq_document/repository/auth/auth_repository.dart' as _i18;
import 'package:rag_faq_document/repository/chat/chat_repository.dart' as _i26;
import 'package:rag_faq_document/repository/dio/authenticated_dio_client.dart'
    as _i11;
import 'package:rag_faq_document/repository/local_storage/local_storage.dart'
    as _i9;
import 'package:rag_faq_document/repository/message/message_repository.dart'
    as _i29;
import 'package:rag_faq_document/repository/upload/upload_repository.dart'
    as _i27;
import 'package:rag_faq_document/services/auth/auth_service.dart' as _i30;
import 'package:rag_faq_document/utils/utils.dart' as _i21;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIOSOptions_0 extends _i1.SmartFake implements _i2.IOSOptions {
  _FakeIOSOptions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_1 extends _i1.SmartFake
    implements _i2.AndroidOptions {
  _FakeAndroidOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_2 extends _i1.SmartFake implements _i2.LinuxOptions {
  _FakeLinuxOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_3 extends _i1.SmartFake
    implements _i2.WindowsOptions {
  _FakeWindowsOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_4 extends _i1.SmartFake implements _i2.WebOptions {
  _FakeWebOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_5 extends _i1.SmartFake implements _i2.MacOsOptions {
  _FakeMacOsOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_6 extends _i1.SmartFake implements _i3.BaseOptions {
  _FakeBaseOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_7 extends _i1.SmartFake
    implements _i4.HttpClientAdapter {
  _FakeHttpClientAdapter_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_8 extends _i1.SmartFake implements _i5.Transformer {
  _FakeTransformer_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_9 extends _i1.SmartFake implements _i6.Interceptors {
  _FakeInterceptors_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_10<T1> extends _i1.SmartFake implements _i7.Response<T1> {
  _FakeResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_11 extends _i1.SmartFake implements _i8.Dio {
  _FakeDio_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalStorage_12 extends _i1.SmartFake implements _i9.LocalStorage {
  _FakeLocalStorage_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultipartFile_13 extends _i1.SmartFake implements _i8.MultipartFile {
  _FakeMultipartFile_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_14 extends _i1.SmartFake implements _i10.UserResponse {
  _FakeUserResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthenticatedDioClient_15 extends _i1.SmartFake
    implements _i11.AuthenticatedDioClient {
  _FakeAuthenticatedDioClient_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChat_16 extends _i1.SmartFake implements _i12.Chat {
  _FakeChat_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRef_17<State extends Object?> extends _i1.SmartFake
    implements _i13.Ref<State> {
  _FakeRef_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadPresign_18 extends _i1.SmartFake
    implements _i14.UploadPresign {
  _FakeUploadPresign_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadResponse_19 extends _i1.SmartFake
    implements _i15.UploadResponse {
  _FakeUploadResponse_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentStatusResponse_20 extends _i1.SmartFake
    implements _i16.DocumentStatusResponse {
  _FakeDocumentStatusResponse_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessage_21 extends _i1.SmartFake implements _i17.Message {
  _FakeMessage_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_22 extends _i1.SmartFake
    implements _i18.AuthRepository {
  _FakeAuthRepository_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i2.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_0(this, Invocation.getter(#iOptions)),
          )
          as _i2.IOSOptions);

  @override
  _i2.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_1(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i2.AndroidOptions);

  @override
  _i2.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_2(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i2.LinuxOptions);

  @override
  _i2.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_3(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i2.WindowsOptions);

  @override
  _i2.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_4(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i2.WebOptions);

  @override
  _i2.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_5(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i2.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i19.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i19.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i20.Future<void> write({
    required String? key,
    required String? value,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<String?> read({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i20.Future<String?>.value(),
          )
          as _i20.Future<String?>);

  @override
  _i20.Future<bool> containsKey({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i20.Future<bool>.value(false),
          )
          as _i20.Future<bool>);

  @override
  _i20.Future<void> delete({
    required String? key,
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<Map<String, String>> readAll({
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i20.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i20.Future<Map<String, String>>);

  @override
  _i20.Future<void> deleteAll({
    _i2.IOSOptions? iOptions,
    _i2.AndroidOptions? aOptions,
    _i2.LinuxOptions? lOptions,
    _i2.WebOptions? webOptions,
    _i2.MacOsOptions? mOptions,
    _i2.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i20.Future<bool?>.value(),
          )
          as _i20.Future<bool?>);
}

/// A class which mocks [DeviceInfoWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoWrapper extends _i1.Mock implements _i21.DeviceInfoWrapper {
  MockDeviceInfoWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<String> getDeviceName() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceName, []),
            returnValue: _i20.Future<String>.value(
              _i22.dummyValue<String>(
                this,
                Invocation.method(#getDeviceName, []),
              ),
            ),
          )
          as _i20.Future<String>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i8.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_6(this, Invocation.getter(#options)),
          )
          as _i3.BaseOptions);

  @override
  _i4.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_7(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i4.HttpClientAdapter);

  @override
  _i5.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_8(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i5.Transformer);

  @override
  _i6.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_9(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i6.Interceptors);

  @override
  set options(_i3.BaseOptions? _options) => super.noSuchMethod(
    Invocation.setter(#options, _options),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i4.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i5.Transformer? _transformer) => super.noSuchMethod(
    Invocation.setter(#transformer, _transformer),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i20.Future<_i7.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i23.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i3.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i23.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i3.FileAccessMode? fileAccessMode = _i3.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i20.Future<_i7.Response<dynamic>>.value(
              _FakeResponse_10<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<dynamic>>);

  @override
  _i20.Future<_i7.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i3.ProgressCallback? onReceiveProgress,
    _i23.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i3.FileAccessMode? fileAccessMode = _i3.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i20.Future<_i7.Response<dynamic>>.value(
              _FakeResponse_10<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<dynamic>>);

  @override
  _i20.Future<_i7.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i23.CancelToken? cancelToken,
    _i3.Options? options,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i23.CancelToken? cancelToken,
    _i3.Options? options,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i20.Future<_i7.Response<T>> fetch<T>(_i3.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i20.Future<_i7.Response<T>>.value(
              _FakeResponse_10<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i20.Future<_i7.Response<T>>);

  @override
  _i8.Dio clone({
    _i3.BaseOptions? options,
    _i6.Interceptors? interceptors,
    _i4.HttpClientAdapter? httpClientAdapter,
    _i5.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_11(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i8.Dio);
}

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i9.LocalStorage {
  MockLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<void> setAccess(String? v) =>
      (super.noSuchMethod(
            Invocation.method(#setAccess, [v]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<String?> loadRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#loadRefresh, []),
            returnValue: _i20.Future<String?>.value(),
          )
          as _i20.Future<String?>);

  @override
  _i20.Future<void> saveRefresh(String? v) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefresh, [v]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);
}

/// A class which mocks [AuthenticatedDioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticatedDioClient extends _i1.Mock
    implements _i11.AuthenticatedDioClient {
  MockAuthenticatedDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_11(this, Invocation.getter(#dio)),
          )
          as _i8.Dio);

  @override
  _i9.LocalStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeLocalStorage_12(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i9.LocalStorage);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i22.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i24.VoidCallback get onUnauthorized =>
      (super.noSuchMethod(
            Invocation.getter(#onUnauthorized),
            returnValue: () {},
          )
          as _i24.VoidCallback);

  @override
  _i20.Future<String> Function() get deviceInfoGetter =>
      (super.noSuchMethod(
            Invocation.getter(#deviceInfoGetter),
            returnValue:
                () => _i20.Future<String>.value(
                  _i22.dummyValue<String>(
                    this,
                    Invocation.getter(#deviceInfoGetter),
                  ),
                ),
          )
          as _i20.Future<String> Function());

  @override
  _i8.Dio Function(_i3.BaseOptions) get refreshDioFactory =>
      (super.noSuchMethod(
            Invocation.getter(#refreshDioFactory),
            returnValue:
                (_i3.BaseOptions __p0) =>
                    _FakeDio_11(this, Invocation.getter(#refreshDioFactory)),
          )
          as _i8.Dio Function(_i3.BaseOptions));
}

/// A class which mocks [MultipartFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultipartFile extends _i1.Mock implements _i8.MultipartFile {
  MockMultipartFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get length =>
      (super.noSuchMethod(Invocation.getter(#length), returnValue: 0) as int);

  @override
  bool get isFinalized =>
      (super.noSuchMethod(Invocation.getter(#isFinalized), returnValue: false)
          as bool);

  @override
  _i20.Stream<_i25.Uint8List> finalize() =>
      (super.noSuchMethod(
            Invocation.method(#finalize, []),
            returnValue: _i20.Stream<_i25.Uint8List>.empty(),
          )
          as _i20.Stream<_i25.Uint8List>);

  @override
  _i8.MultipartFile clone() =>
      (super.noSuchMethod(
            Invocation.method(#clone, []),
            returnValue: _FakeMultipartFile_13(
              this,
              Invocation.method(#clone, []),
            ),
          )
          as _i8.MultipartFile);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i18.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_11(this, Invocation.getter(#dio)),
          )
          as _i8.Dio);

  @override
  _i20.Future<String> Function() get getDeviceInfoFn =>
      (super.noSuchMethod(
            Invocation.getter(#getDeviceInfoFn),
            returnValue:
                () => _i20.Future<String>.value(
                  _i22.dummyValue<String>(
                    this,
                    Invocation.getter(#getDeviceInfoFn),
                  ),
                ),
          )
          as _i20.Future<String> Function());

  @override
  _i20.Future<void> signUp({
    required String? username,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #username: username,
              #email: email,
              #password: password,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i10.UserResponse> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i20.Future<_i10.UserResponse>.value(
              _FakeUserResponse_14(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i20.Future<_i10.UserResponse>);

  @override
  _i20.Future<void> passwordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#passwordReset, [email]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i10.UserResponse> refreshAccessToken(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refreshAccessToken, [refreshToken]),
            returnValue: _i20.Future<_i10.UserResponse>.value(
              _FakeUserResponse_14(
                this,
                Invocation.method(#refreshAccessToken, [refreshToken]),
              ),
            ),
          )
          as _i20.Future<_i10.UserResponse>);

  @override
  _i20.Future<void> logout({required String? refreshToken}) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#refreshToken: refreshToken}),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i26.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.AuthenticatedDioClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeAuthenticatedDioClient_15(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i11.AuthenticatedDioClient);

  @override
  _i20.Future<List<_i12.Chat>> listChats({
    required int? pageId,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listChats, [], {
              #pageId: pageId,
              #pageSize: pageSize,
            }),
            returnValue: _i20.Future<List<_i12.Chat>>.value(<_i12.Chat>[]),
          )
          as _i20.Future<List<_i12.Chat>>);

  @override
  _i20.Future<_i12.Chat> getChat({required int? id}) =>
      (super.noSuchMethod(
            Invocation.method(#getChat, [], {#id: id}),
            returnValue: _i20.Future<_i12.Chat>.value(
              _FakeChat_16(this, Invocation.method(#getChat, [], {#id: id})),
            ),
          )
          as _i20.Future<_i12.Chat>);

  @override
  _i20.Future<_i12.Chat> createChat({
    required int? documentId,
    required String? title,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChat, [], {
              #documentId: documentId,
              #title: title,
            }),
            returnValue: _i20.Future<_i12.Chat>.value(
              _FakeChat_16(
                this,
                Invocation.method(#createChat, [], {
                  #documentId: documentId,
                  #title: title,
                }),
              ),
            ),
          )
          as _i20.Future<_i12.Chat>);
}

/// A class which mocks [UploadRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadRepository extends _i1.Mock implements _i27.UploadRepository {
  MockUploadRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Ref<Object?> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeRef_17<Object?>(this, Invocation.getter(#ref)),
          )
          as _i13.Ref<Object?>);

  @override
  _i11.AuthenticatedDioClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeAuthenticatedDioClient_15(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i11.AuthenticatedDioClient);

  @override
  _i8.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_11(this, Invocation.getter(#dio)),
          )
          as _i8.Dio);

  @override
  _i20.Future<_i14.UploadPresign> presign({
    required String? fileName,
    required String? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#presign, [], {
              #fileName: fileName,
              #mimeType: mimeType,
            }),
            returnValue: _i20.Future<_i14.UploadPresign>.value(
              _FakeUploadPresign_18(
                this,
                Invocation.method(#presign, [], {
                  #fileName: fileName,
                  #mimeType: mimeType,
                }),
              ),
            ),
          )
          as _i20.Future<_i14.UploadPresign>);

  @override
  _i20.Future<void> uploadS3({
    required String? presignedUrl,
    required _i28.File? file,
    required String? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadS3, [], {
              #presignedUrl: presignedUrl,
              #file: file,
              #mimeType: mimeType,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i15.UploadResponse> uploadFile({
    required String? filePath,
    required String? filename,
    required String? fileType,
    _i8.MultipartFile? multipartFileForTest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [], {
              #filePath: filePath,
              #filename: filename,
              #fileType: fileType,
              #multipartFileForTest: multipartFileForTest,
            }),
            returnValue: _i20.Future<_i15.UploadResponse>.value(
              _FakeUploadResponse_19(
                this,
                Invocation.method(#uploadFile, [], {
                  #filePath: filePath,
                  #filename: filename,
                  #fileType: fileType,
                  #multipartFileForTest: multipartFileForTest,
                }),
              ),
            ),
          )
          as _i20.Future<_i15.UploadResponse>);

  @override
  _i20.Future<_i16.DocumentStatusResponse> getDocumentStatus(int? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentStatus, [documentId]),
            returnValue: _i20.Future<_i16.DocumentStatusResponse>.value(
              _FakeDocumentStatusResponse_20(
                this,
                Invocation.method(#getDocumentStatus, [documentId]),
              ),
            ),
          )
          as _i20.Future<_i16.DocumentStatusResponse>);

  @override
  _i20.Future<void> cancelUpload(dynamic documentId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelUpload, [documentId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i29.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.AuthenticatedDioClient get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeAuthenticatedDioClient_15(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i11.AuthenticatedDioClient);

  @override
  _i20.Future<_i17.Message> postMessage({
    required String? message,
    required int? sessionId,
    required int? documentId,
    required String? title,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postMessage, [], {
              #message: message,
              #sessionId: sessionId,
              #documentId: documentId,
              #title: title,
            }),
            returnValue: _i20.Future<_i17.Message>.value(
              _FakeMessage_21(
                this,
                Invocation.method(#postMessage, [], {
                  #message: message,
                  #sessionId: sessionId,
                  #documentId: documentId,
                  #title: title,
                }),
              ),
            ),
          )
          as _i20.Future<_i17.Message>);

  @override
  _i20.Future<List<_i17.Message>> listMessage({required int? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#listMessage, [], {#sessionId: sessionId}),
            returnValue: _i20.Future<List<_i17.Message>>.value(
              <_i17.Message>[],
            ),
          )
          as _i20.Future<List<_i17.Message>>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i30.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.LocalStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeLocalStorage_12(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i9.LocalStorage);

  @override
  _i18.AuthRepository get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeAuthRepository_22(this, Invocation.getter(#repo)),
          )
          as _i18.AuthRepository);

  @override
  _i13.Ref<Object?> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeRef_17<Object?>(this, Invocation.getter(#ref)),
          )
          as _i13.Ref<Object?>);

  @override
  _i20.Future<void> signup({
    required String? username,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [], {
              #username: username,
              #email: email,
              #password: password,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> passwordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#passwordReset, [email]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> refreshAccessToken(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refreshAccessToken, [refreshToken]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);
}
